const particlesConfig = {
    "particles":{
        "number":{
            "value": 80,
            "density":{
            "enable":true,
            "value_area":600
            }
        },
        "color":{
            "value":"#ffffff"
        },
        "shape":{
            "type":"circle",
            "stroke":{
                "width":0,
                "color":"#000000"
            },
        },
        "opacity":{
            "value":0.5,
            "random":false,
            "anim":{
                "enable":false,
                "speed":1,
                "opacity_min":0.1,
                "sync":false
            }
        },
        "size":{
            "value":2,
            "random":true,
            "anim":{
                "enable":false,
                "speed":40,
                "size_min":0.1,
                "sync":false
            }
        },
        "line_linked":{
            "enable":true,
            "distance":150,
            "color":"#ffffff",
            "opacity":0.4,
            "width":1
        },
        "move":{
            "enable":true,
            "speed":5,
            "direction":"none",
            "random":false,
            "out_mode":"out",
        }
    },
    "interactivity":{
        "detect_on":"canvas",
        "events":{
        "onhover":{
            "enable":false,
        },
        "onclick":{
            "enable":false,
        },
        },
        "modes":{
            "grab":{
                "distance":400,
                "line_linked":{
                "opacity":1
                }
            },
        }
    },
    "retina_detect":true,
    "resize":true
}

export default particlesConfig;